[Watcher]
GamePath = 'E:\Program Files\ACLOS\Launcher\无畏契约登录器.exe'
Width = 1440
Height = 1080
Fps = 144

[Valorant]
LauncherPath = 'E:\Program Files\ACLOS\Launcher\无畏契约登录器.exe'
GamePath = 'E:\Games\Tencent Games\VALORANT\live'

[Development]
Debug = false
